github.com:
    users:
        mohammedazimpatel05-dot:
            oauth_token: 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
    git_protocol: https
    user: mohammedazimpatel05-dot
    oauth_token: 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
